"""Section 5: Complexity theory — P, NP, NP-completeness, and space."""

CARDS = [
    dict(
        q="How is the <b>running time</b> of a Turing machine defined?",
        a="f(n) = the maximum number of steps the machine takes over all inputs of length n — i.e. <b>worst case</b>, as a function of <b>input length</b>.",
        ex="Complexity theory shifts the question from 'is it solvable at all?' (computability) to 'is it solvable in reasonable time/space?'.",
        pt="complexidade de tempo",
        tags=["complexity", "definition"],
    ),
    dict(
        q="Define <b>big-O</b> and <b>little-o</b> notation.",
        a="<b>f(n) = O(g(n))</b>: ∃ c, n₀ such that f(n) ≤ c·g(n) for all n ≥ n₀ — asymptotic <b>upper bound</b> ('grows no faster').<br><b>f(n) = o(g(n))</b>: lim<sub>n→∞</sub> f(n)/g(n) = 0 — <b>strictly slower</b> growth.",
        ex="5n³ + 2n = O(n³); n log n = o(n²); but n² ≠ o(n²). Constants and low-order terms are deliberately ignored.",
        pt="notação assintótica O e o",
        tags=["complexity", "definition"],
    ),
    dict(
        q="Define the class <b>TIME(t(n))</b> and the class <b>P</b>.",
        a="TIME(t(n)) = languages decidable by a (deterministic, single-tape) TM in O(t(n)) time.<br><b>P = ⋃<sub>k</sub> TIME(nᵏ)</b> — languages decidable in <b>polynomial time</b>.",
        ex="P is the theoretical stand-in for 'efficiently solvable / tractable'. n, n log n, n³ ∈ P-territory; 2ⁿ is not polynomial.",
        pt="classe P (tempo polinomial)",
        tags=["complexity", "definition"],
    ),
    dict(
        q="Why is <b>P robust</b> (model-independent), and why do we equate it with 'feasible'?",
        a="All reasonable deterministic models (multitape TM, RAM, your laptop) simulate each other with only <b>polynomial overhead</b>, so P is the same class in all of them.<br>Polynomials compose (poly of poly = poly) and grow moderately — while exponentials explode (2¹⁰⁰ steps is beyond the universe).",
        ex="This robustness is why the theory can ignore hardware details, and why 'polynomial vs exponential' is the fundamental divide.",
        pt="robustez da classe P",
        tags=["complexity", "bigpicture"],
    ),
    dict(
        q="Name problems known to be in <b>P</b> (with the algorithm idea).",
        a="• <b>PATH</b> (is there a path s→t in a directed graph?) — BFS/DFS<br>• <b>RELPRIME</b> (gcd(x,y)=1?) — Euclidean algorithm<br>• <b>Every context-free language</b> — CYK dynamic programming, O(n³)<br>• PRIMES (nontrivial result, AKS 2002)",
        ex="Careful with numbers: input size is the number of <b>digits</b> (log of the value). Trial division is exponential in the digit count — that's why Euclid/AKS matter.",
        pt="exemplos de problemas em P",
        tags=["complexity"],
    ),
    dict(
        q="Define the class <b>NP</b> — both definitions.",
        a="<b>Verifier definition:</b> L ∈ NP iff there is a polynomial-time <b>verifier</b> V: w ∈ L ⟺ ∃ certificate c (of polynomial length) with V(w, c) accepting.<br><b>Machine definition:</b> L ∈ NP iff some <b>nondeterministic</b> TM decides L in polynomial time.<br>The two definitions are equivalent (certificate = the sequence of nondeterministic choices).",
        ex="Slogan: <b>NP = solutions may be hard to FIND but are easy to CHECK</b>. A sudoku solution is checked in seconds regardless of how long it took to find.",
        pt="classe NP",
        tags=["complexity", "definition"],
    ),
    dict(
        q="⚠ What does NP stand for — and what does it <b>not</b> mean?",
        a="<b>N</b>ondeterministic <b>P</b>olynomial time. It does <b>NOT</b> mean 'non-polynomial'! P ⊆ NP: every problem solvable in poly time is also verifiable in poly time (certificate can be empty).",
        ex="Extremely common misconception — saying 'NP = not polynomial' in an exam is an instant red flag.",
        pt="NP ≠ 'não polinomial'",
        tags=["complexity", "trap"],
    ),
    dict(
        q="Give classic problems in <b>NP</b> and their certificates.",
        a="• <b>SAT</b> — a satisfying truth assignment<br>• <b>CLIQUE</b> (k-clique in G?) — the set of k vertices<br>• <b>HAMPATH</b> — the Hamiltonian path itself<br>• <b>SUBSET-SUM</b> — the subset that hits the target<br>• <b>3-COLORING</b> — the coloring<br>Each certificate is short and checkable in polynomial time.",
        ex="To show L ∈ NP on an exam: say what the certificate is, and why checking it takes polynomial time. Two sentences.",
        pt="exemplos de problemas em NP",
        tags=["complexity"],
    ),
    dict(
        q="What is the <b>P vs NP</b> question, and what is known?",
        a="Question: does <b>P = NP</b>? (Can every efficiently <i>verifiable</i> problem also be efficiently <i>solved</i>?)<br>Known: P ⊆ NP ⊆ EXPTIME; P ≠ EXPTIME. <b>Whether P = NP is open</b> — the most famous problem in computer science (Clay Millennium Prize, US$1,000,000). Most experts believe P ≠ NP.",
        ex="If P = NP: cryptography as we know it collapses, and finding proofs becomes as easy as checking them.",
        pt="problema P vs NP",
        tags=["complexity", "bigpicture"],
    ),
    dict(
        q="Define <b>polynomial-time reduction</b> A ≤<sub>p</sub> B and its key property.",
        a="A ≤<sub>p</sub> B iff a <b>polynomial-time computable</b> function f exists with w ∈ A ⟺ f(w) ∈ B.<br>Key property: if B ∈ P then A ∈ P (compose: poly-time translate, then poly-time solve). Contrapositive: if A is hard, B is hard.",
        ex="Same idea as mapping reduction from computability, with a poly-time budget. Transitive: A ≤<sub>p</sub> B ≤<sub>p</sub> C ⟹ A ≤<sub>p</sub> C — this is what lets hardness spread from SAT to thousands of problems.",
        pt="redução em tempo polinomial",
        tags=["complexity", "reduction", "definition"],
    ),
    dict(
        q="Define <b>NP-hard</b> and <b>NP-complete</b>.",
        a="<b>NP-hard:</b> every language in NP poly-time reduces to it (A ≤<sub>p</sub> B for all A ∈ NP). (Need not itself be in NP.)<br><b>NP-complete:</b> NP-hard <b>and</b> in NP — the 'hardest problems inside NP'.",
        ex="If ANY single NP-complete problem has a poly-time algorithm, then <b>P = NP</b>. If any single one is outside P, then P ≠ NP. They stand or fall together.",
        pt="NP-difícil; NP-completo",
        tags=["complexity", "definition"],
    ),
    dict(
        q="State the <b>Cook–Levin theorem</b> and the idea of its proof.",
        a="<b>SAT is NP-complete</b> (Cook 1971, Levin 1973).<br>Idea: SAT ∈ NP (certificate = assignment). Hardness: for any NP language A with NTM N, build a Boolean formula that says 'there is an accepting <b>computation tableau</b> of N on w' — variables encode which symbol is in each cell of the (poly × poly) table of configurations; clauses enforce the start configuration, legal 2×3 window moves, and acceptance.",
        ex="The profound point: Boolean logic can simulate computation. One concrete problem captures ALL of NP.",
        pt="teorema de Cook–Levin",
        tags=["complexity", "theorem", "keyproof"],
    ),
    dict(
        q="What is <b>3SAT</b>, and is it NP-complete? What about <b>2SAT</b>?",
        a="3SAT = satisfiability of CNF formulas with exactly 3 literals per clause. <b>NP-complete</b> (SAT reduces to it by splitting long clauses with new variables).<br><b>2SAT ∈ P</b> — solvable in linear time via implication graphs and strongly connected components.",
        ex="The 2-vs-3 boundary is a recurring theme: 2SAT easy / 3SAT hard; 2-coloring easy / 3-coloring hard; Euler path easy / Hamiltonian path hard.",
        pt="3SAT vs 2SAT",
        tags=["complexity"],
    ),
    dict(
        q="Sketch the reduction <b>3SAT ≤<sub>p</sub> CLIQUE</b>.",
        a="From a 3CNF formula with k clauses build a graph:<br>• one <b>node per literal occurrence</b>, grouped in triples by clause<br>• edges between all pairs of nodes in <b>different clauses</b>, except pairs of <b>contradictory literals</b> (x and x̄)<br>Formula satisfiable ⟺ graph has a <b>k-clique</b> (pick one true literal per clause; they're pairwise compatible).",
        ex="This is the canonical example of a 'gadget' reduction — learn its shape: local structures encode choices, edges encode consistency.",
        pt="redução 3SAT → CLIQUE",
        tags=["complexity", "reduction", "keyproof"],
    ),
    dict(
        q="Give the standard <b>recipe to prove a problem X is NP-complete</b>.",
        a="1. <b>X ∈ NP</b>: describe a certificate + poly-time verifier.<br>2. <b>X is NP-hard</b>: pick a known NP-complete problem K and build a poly-time reduction <b>K ≤<sub>p</sub> X</b> (from the KNOWN problem TO yours!), proving w ∈ K ⟺ f(w) ∈ X in both directions.",
        ex="Direction trap again: reducing X to SAT proves nothing (everything in NP reduces to SAT). You must reduce SAT (or another NPC problem) to X.",
        pt="receita de prova de NP-completude",
        tags=["complexity", "reduction", "technique"],
    ),
    dict(
        q="Name six famous <b>NP-complete</b> problems.",
        a="• <b>SAT / 3SAT</b><br>• <b>CLIQUE</b><br>• <b>INDEPENDENT-SET</b> and <b>VERTEX-COVER</b><br>• <b>HAMPATH / HAMCYCLE</b> (and <b>TSP</b> decision version)<br>• <b>SUBSET-SUM</b> (and PARTITION, KNAPSACK)<br>• <b>3-COLORING</b>",
        ex="CLIQUE, IS, VC are 'the same problem in disguise': S is an independent set ⟺ S is a clique in the complement graph ⟺ V∖S is a vertex cover.",
        pt="problemas NP-completos famosos",
        tags=["complexity"],
    ),
    dict(
        q="Your boss asks you to solve a problem and you discover it's <b>NP-complete</b>. What do you (a theorist) conclude and (a practitioner) do?",
        a="Conclude: no known polynomial algorithm; one is unlikely to exist (unless P = NP) — don't waste weeks seeking an exact fast general algorithm.<br>Do instead: <b>approximation algorithms</b>, <b>heuristics</b> (SAT solvers work well in practice!), <b>exponential algorithms for small inputs</b>, or exploit <b>special structure</b> of your instances.",
        ex="NP-completeness is a statement about worst-case general instances — real-world instances are often much friendlier.",
        pt="lidando com NP-completude na prática",
        tags=["complexity", "bigpicture"],
    ),
    dict(
        q="Define <b>coNP</b>. What is the relationship between NP and coNP?",
        a="coNP = {L : L̄ ∈ NP} — problems where <b>'no' answers</b> have short certificates. Example: TAUTOLOGY, UNSAT.<br>Relationship: <b>unknown whether NP = coNP</b> (believed not). P ⊆ NP ∩ coNP. If some NP-complete problem were in coNP, then NP = coNP.",
        ex="Mirror intuition: NP certifies YES ('here is a satisfying assignment'); coNP certifies NO ('here is why none exists' — usually no short proof known).",
        pt="classe coNP",
        tags=["complexity", "definition"],
    ),
    dict(
        q="Define <b>SPACE(f(n))</b>, <b>PSPACE</b>, and state where PSPACE sits relative to P and NP.",
        a="SPACE(f(n)) = languages decidable using O(f(n)) <b>tape cells</b>. PSPACE = polynomial space.<br><b>P ⊆ NP ⊆ PSPACE ⊆ EXPTIME</b>. None of the individual inclusions is known to be strict — but P ⊊ EXPTIME, so at least one of them is!",
        ex="Why NP ⊆ PSPACE: try all certificates one by one, reusing the same space. Space is reusable; time is not — that asymmetry drives the theory.",
        pt="classes de espaço; PSPACE",
        tags=["complexity", "definition"],
    ),
    dict(
        q="State <b>Savitch's theorem</b> and its most-quoted consequence.",
        a="<b>NSPACE(f(n)) ⊆ SPACE(f(n)²)</b> for f(n) ≥ log n — nondeterminism can be removed at only quadratic cost in <b>space</b>.<br>Consequence: <b>PSPACE = NPSPACE</b> (squaring a polynomial gives a polynomial).",
        ex="Proof gadget: the recursive reachability procedure — 'can config c₁ reach c₂ in ≤ 2ᵗ steps?' checks a midpoint recursively, reusing space. Contrast with time, where removing nondeterminism seems to cost exponential (P vs NP!).",
        pt="teorema de Savitch",
        tags=["complexity", "theorem"],
    ),
    dict(
        q="What is <b>TQBF</b>, and what is it complete for?",
        a="TQBF = {true fully quantified Boolean formulas, e.g. ∀x∃y (x∨y)∧(x̄∨ȳ)}. It is <b>PSPACE-complete</b> — the 'SAT of PSPACE'.",
        ex="Intuition: alternating ∀/∃ quantifiers = optimal play in games. Generalized versions of chess/Go/geography are PSPACE-hard (or worse) for this reason.",
        pt="TQBF é PSPACE-completo",
        tags=["complexity"],
    ),
    dict(
        q="What do the <b>hierarchy theorems</b> say, informally?",
        a="Given genuinely more time (or space), TMs can decide strictly more languages:<br>• Time hierarchy: TIME(t(n)) ⊊ TIME(t(n)·log t(n)·ω(1)) roughly — e.g. TIME(n) ⊊ TIME(n²).<br>• Space hierarchy: SPACE(f(n)) ⊊ SPACE(g(n)) when f = o(g).<br>Proved by <b>diagonalization</b>. Consequence: <b>P ⊊ EXPTIME</b>, NL ⊊ PSPACE.",
        ex="These are among the few PROVEN separations. Diagonalization gives 'more resources = more power' but frustratingly cannot settle P vs NP.",
        pt="teoremas de hierarquia",
        tags=["complexity", "theorem"],
    ),
    dict(
        q="Define the classes <b>L</b> and <b>NL</b>, and name the canonical NL-complete problem.",
        a="L = problems decidable in <b>logarithmic space</b> (read-only input tape + O(log n) work tape). NL = nondeterministic log space.<br>Canonical NL-complete problem: <b>PATH</b> (s–t reachability in a directed graph), under log-space reductions.",
        ex="Log space ≈ 'a constant number of pointers/counters into the input'. Known: L ⊆ NL ⊆ P, and NL = coNL (Immerman–Szelepcsényi — a surprise!). L vs NL is open.",
        pt="classes L e NL",
        tags=["complexity", "definition"],
    ),
    dict(
        q="Draw the final <b>map of complexity classes</b> with the known strict separations.",
        a="<b>L ⊆ NL ⊆ P ⊆ NP ⊆ PSPACE = NPSPACE ⊆ EXPTIME</b><br>Known strict: NL ⊊ PSPACE and P ⊊ EXPTIME (hierarchy theorems).<br>Everything else (L vs NL, P vs NP, NP vs PSPACE, …) is <b>open</b>.",
        ex="Mental picture: a chain of nested circles where we can prove the far ends differ, but no two adjacent circles have ever been separated. This picture ends the course — and is a classic final-exam question.",
        pt="mapa das classes de complexidade",
        tags=["complexity", "bigpicture"],
    ),
]
