"""Section 4: Decidability, undecidability, and reductions."""

CARDS = [
    dict(
        q="Which classic problems about <b>DFAs/NFAs/regexes</b> are decidable?",
        a="All of these are <b>decidable</b>:<br>• A<sub>DFA</sub> = {⟨M,w⟩ : DFA M accepts w} — simulate<br>• A<sub>NFA</sub>, A<sub>REX</sub> — convert to DFA, then simulate<br>• E<sub>DFA</sub> = {⟨M⟩ : L(M) = ∅} — reachability check<br>• EQ<sub>DFA</sub> = {⟨M₁,M₂⟩ : L(M₁) = L(M₂)} — emptiness of symmetric difference",
        ex="Note the pattern of these proofs: describe a high-level always-halting algorithm; the Church–Turing thesis lets you skip building the TM explicitly.",
        pt="problemas decidíveis de autômatos",
        tags=["decidability"],
    ),
    dict(
        q="Are A<sub>CFG</sub> (membership) and E<sub>CFG</sub> (emptiness) decidable? What about EQ<sub>CFG</sub>?",
        a="A<sub>CFG</sub>: <b>decidable</b> — convert G to Chomsky Normal Form, test all derivations of exactly 2n−1 steps (or run CYK).<br>E<sub>CFG</sub>: <b>decidable</b> — iteratively mark variables that can generate terminal strings; check if S is marked.<br>EQ<sub>CFG</sub>: <b>UNdecidable</b> — the symmetric-difference trick fails because CFLs aren't closed under intersection/complement.",
        ex="Consequence of A<sub>CFG</sub> decidable: <b>every CFL is decidable</b> (hardwire G, run the membership decider).",
        pt="decidibilidade para GLCs",
        tags=["decidability"],
    ),
    dict(
        q="Define <b>A<sub>TM</sub></b>. Is it recognizable? Is it decidable?",
        a="A<sub>TM</sub> = {⟨M, w⟩ : M is a TM and M accepts w}.<br>• <b>Turing-recognizable</b>: the universal TM U simulates M on w and accepts if M does.<br>• <b>UNDECIDABLE</b>: if M loops on w, U loops too — and no clever trick can fix this (diagonalization).",
        ex="A<sub>TM</sub> is THE central undecidable problem — almost every other undecidability proof reduces from it.",
        pt="problema da aceitação A<sub>TM</sub>",
        tags=["decidability", "keyproof"],
    ),
    dict(
        q="Give the <b>diagonalization proof that A<sub>TM</sub> is undecidable</b>.",
        a="Suppose decider H decides A<sub>TM</sub> (H(⟨M,w⟩) = accept iff M accepts w). Build TM <b>D</b>: on input ⟨M⟩, run H on ⟨M, ⟨M⟩⟩ and <b>output the opposite</b>.<br>Now run D on ⟨D⟩: D accepts ⟨D⟩ ⟺ H says D rejects ⟨D⟩ ⟺ D rejects ⟨D⟩. Contradiction ⟹ H cannot exist.",
        ex="It's Cantor's diagonal flip: D differs from every machine Mᵢ on input ⟨Mᵢ⟩ — in particular from itself. Compare: 'this sentence is false.'",
        pt="prova da indecidibilidade de A<sub>TM</sub>",
        tags=["decidability", "keyproof"],
    ),
    dict(
        q="State the <b>halting problem</b> and its status. How is it proved undecidable?",
        a="HALT<sub>TM</sub> = {⟨M,w⟩ : M halts on input w}. <b>Undecidable.</b><br>Proof by reduction from A<sub>TM</sub>: with a decider R for HALT<sub>TM</sub>, decide A<sub>TM</sub> as: run R on ⟨M,w⟩; if 'never halts', reject; if 'halts', simulate M on w safely and answer. This would decide A<sub>TM</sub> — impossible.",
        ex="Practical meaning: no program can analyze arbitrary code and always correctly predict 'will this terminate?'.",
        pt="problema da parada",
        tags=["decidability", "keyproof"],
    ),
    dict(
        q="Is the <b>complement of A<sub>TM</sub></b> Turing-recognizable?",
        a="<b>No.</b> A<sub>TM</sub> is recognizable; if its complement were also recognizable, A<sub>TM</sub> would be decidable (run both recognizers in parallel) — contradiction.",
        ex="So the complement of A<sub>TM</sub> is the standard example of a language that is not even recognizable. General rule: undecidable + recognizable ⟹ complement not recognizable.",
        pt="co-A<sub>TM</sub> não é reconhecível",
        tags=["decidability", "keyproof"],
    ),
    dict(
        q="Define <b>mapping reduction</b> A ≤<sub>m</sub> B and its two key consequences.",
        a="A ≤<sub>m</sub> B iff there is a <b>computable function</b> f: Σ* → Σ* with w ∈ A ⟺ f(w) ∈ B for every w.<br>Consequences:<br>• If B is decidable (or recognizable), so is A.<br>• Contrapositive: if A is undecidable, <b>B is undecidable too</b>.",
        ex="Read '≤' as 'is no harder than'. To use it: transform instances of the KNOWN-hard problem into instances of YOUR problem, preserving yes/no.",
        pt="redução por mapeamento (redução-m)",
        tags=["decidability", "reduction", "definition"],
    ),
    dict(
        q="⚠ In an undecidability proof, which <b>direction</b> must the reduction go — and what is the classic mistake?",
        a="Reduce the <b>known undecidable problem TO the new problem</b>: A<sub>TM</sub> ≤<sub>m</sub> NEW. ('If NEW were decidable, I could decide A<sub>TM</sub>.')<br>The classic mistake is reducing NEW ≤ A<sub>TM</sub> — that only shows NEW is <i>no harder</i> than A<sub>TM</sub>, which proves nothing about hardness.",
        ex="Sanity check for exams: your proof should END with 'therefore I can decide A<sub>TM</sub>, contradiction'. Same direction rule applies to NP-hardness reductions later.",
        pt="direção da redução",
        tags=["decidability", "reduction", "trap"],
    ),
    dict(
        q="Sketch the proof that <b>E<sub>TM</sub></b> = {⟨M⟩ : L(M) = ∅} is undecidable.",
        a="Reduce from A<sub>TM</sub>. Given ⟨M, w⟩, build M₁: 'on input x, if x ≠ w reject; if x = w, run M on w and accept if M accepts.'<br>Then L(M₁) = {w} if M accepts w, and ∅ otherwise. A decider for E<sub>TM</sub> applied to ⟨M₁⟩ would decide A<sub>TM</sub>.",
        ex="Master template: build a machine whose language <i>encodes the answer</i> to the A<sub>TM</sub> question, then ask the supposed decider about it.",
        pt="indecidibilidade do problema da vacuidade",
        tags=["decidability", "reduction", "keyproof"],
    ),
    dict(
        q="Is <b>EQ<sub>TM</sub></b> = {⟨M₁,M₂⟩ : L(M₁) = L(M₂)} decidable? Recognizable?",
        a="Neither! EQ<sub>TM</sub> is <b>neither Turing-recognizable nor co-Turing-recognizable</b> — even 'harder' than A<sub>TM</sub>. (Both A<sub>TM</sub> and its complement reduce to it.)",
        ex="Intuition: testing whether two programs are equivalent is hopeless in general — you can't even semi-verify it.",
        pt="equivalência de MTs",
        tags=["decidability", "reduction"],
    ),
    dict(
        q="State <b>Rice's theorem</b>.",
        a="<b>Every nontrivial property of the LANGUAGE of a TM is undecidable.</b><br>Formally: if P is a set of TM descriptions such that (1) membership depends only on L(M) — if L(M₁)=L(M₂) then ⟨M₁⟩∈P ⟺ ⟨M₂⟩∈P — and (2) P is nontrivial (some TM is in P, some is not), then P is undecidable.",
        ex="One theorem, infinitely many corollaries: 'is L(M) empty / regular / finite / contains ε / equals Σ*?' — all undecidable in one shot.",
        pt="teorema de Rice",
        tags=["decidability", "theorem"],
    ),
    dict(
        q="Rice's theorem: which of these is it <b>NOT</b> applicable to?<br>(a) 'L(M) is finite' (b) 'M has exactly 42 states' (c) 'L(M) contains the string 101'",
        a="<b>(b)</b> — that is a property of the <b>machine's syntax</b>, not of its language (two machines with the same language can have different state counts). It's decidable: just count. (a) and (c) are nontrivial <b>semantic</b> properties ⟹ undecidable by Rice.",
        ex="Exam checklist before invoking Rice: ① about the language, not the machine? ② nontrivial (not true of all TMs, not false of all)?",
        pt="quando Rice se aplica",
        tags=["decidability", "trap"],
    ),
    dict(
        q="What is the <b>Post Correspondence Problem (PCP)</b>, and why is it important?",
        a="Given a finite set of dominoes [top/bottom] pairs of strings, decide if some sequence of dominoes (repeats allowed) makes the <b>top concatenation equal the bottom</b>. It is <b>undecidable</b>.",
        ex="Example dominoes: [b/ca], [a/ab], [ca/a], [abc/c] have match a·b·ca·a·abc = ab·ca·a·abc... It matters as a 'combinatorial' undecidable problem used to prove grammar problems (e.g. CFG ambiguity) undecidable.",
        pt="problema da correspondência de Post",
        tags=["decidability"],
    ),
    dict(
        q="What is the difference between a <b>Turing reduction</b> and a <b>mapping reduction</b>?",
        a="<b>Turing reduction (A ≤<sub>T</sub> B):</b> A is decidable given an <b>oracle</b> (subroutine) for B — may call it many times, post-process, negate.<br><b>Mapping reduction (A ≤<sub>m</sub> B):</b> a single computable translation of instances; stronger/more restrictive.<br>A ≤<sub>m</sub> B ⟹ A ≤<sub>T</sub> B, not conversely.",
        ex="Example: A̅<sub>TM</sub> ≤<sub>T</sub> A<sub>TM</sub> trivially (ask and flip), but A̅<sub>TM</sub> ≰<sub>m</sub> A<sub>TM</sub> (mapping reductions preserve recognizability; flipping doesn't).",
        pt="redução de Turing vs. redução por mapeamento",
        tags=["decidability", "reduction"],
    ),
    dict(
        q="Give the <b>general recipe</b> for proving a TM-related problem P undecidable by reduction from A<sub>TM</sub>.",
        a="1. Assume a decider R for P exists.<br>2. From an arbitrary A<sub>TM</sub> instance ⟨M, w⟩, <b>construct a machine M′</b> whose P-status depends exactly on whether M accepts w (M′ typically 'hardcodes' M and w and runs M on w as a first phase).<br>3. Feed ⟨M′⟩ to R; translate the answer into 'M accepts w?'.<br>4. You built a decider for A<sub>TM</sub> — contradiction.",
        ex="The art is step 2: design M′ so that 'M accepts w' flips M′ between having/not having property P. You never actually RUN M′ — you only reason about its language.",
        pt="receita de prova por redução",
        tags=["decidability", "reduction", "technique"],
    ),
    dict(
        q="True or false: 'undecidable' means 'no computer can ever answer the question for any input'.",
        a="<b>False.</b> Undecidable means no <b>single algorithm</b> answers correctly for <b>ALL</b> inputs while always halting. Individual instances may be easy (many specific programs obviously halt).",
        ex="Similarly, an undecidable language can still be recognizable (semi-decidable): you get 'yes' answers eventually, just no guarantee of an answer on 'no' instances.",
        pt="o que 'indecidível' significa (e não significa)",
        tags=["decidability", "trap"],
    ),
    dict(
        q="Status summary — classify each: A<sub>DFA</sub>, A<sub>CFG</sub>, A<sub>TM</sub>, E<sub>DFA</sub>, E<sub>CFG</sub>, E<sub>TM</sub>, EQ<sub>DFA</sub>, EQ<sub>CFG</sub>, EQ<sub>TM</sub>.",
        a="<b>Decidable:</b> A<sub>DFA</sub>, A<sub>CFG</sub>, E<sub>DFA</sub>, E<sub>CFG</sub>, EQ<sub>DFA</sub>.<br><b>Undecidable but recognizable:</b> A<sub>TM</sub>.<br><b>Undecidable, co-recognizable:</b> E<sub>TM</sub> (its complement is recognizable).<br><b>Neither recognizable nor co-recognizable:</b> EQ<sub>TM</sub>.<br>Pattern: everything about DFAs is decidable; CFGs lose equivalence; TMs lose everything (Rice).",
        ex="This table is a guaranteed exam question in some form. The pattern beats memorization: more machine power ⟹ fewer decidable questions about it.",
        pt="tabela de decidibilidade",
        tags=["decidability", "bigpicture"],
    ),
]
