"""Section 0: Mathematical foundations — the language you need before anything else."""

CARDS = [
    dict(
        q="What is an <b>alphabet</b> in computer theory?",
        a="A finite, non-empty set of symbols. Usually written <b>Σ</b> (sigma).",
        ex="Σ = {0, 1} (binary alphabet), Σ = {a, b, …, z}, or even Σ = {🂡, 🂢}. The symbols themselves don't matter — only that there are finitely many.",
        pt="alfabeto",
        tags=["foundations"],
    ),
    dict(
        q="What is a <b>string</b> (or <b>word</b>) over an alphabet Σ?",
        a="A <b>finite sequence</b> of symbols, each taken from Σ.",
        ex="Over Σ = {0,1}: 0, 1, 01, 1101 are strings. A string may use a symbol many times or not at all.",
        pt="palavra / cadeia",
        tags=["foundations"],
    ),
    dict(
        q="What is <b>ε</b> (epsilon) in language theory?",
        a="The <b>empty string</b>: the unique string of length 0, containing no symbols.",
        ex="It is NOT a symbol of the alphabet and NOT the empty set ∅. Concatenating ε with any string w gives w back: εw = wε = w.",
        pt="palavra vazia",
        tags=["foundations"],
    ),
    dict(
        q="What does <b>Σ*</b> mean?",
        a="The set of <b>all finite strings</b> over alphabet Σ — including the empty string ε. (The * is the <i>Kleene star</i>.)",
        ex="For Σ = {a}: Σ* = {ε, a, aa, aaa, …}. Σ* is always infinite (but countable) when Σ is non-empty.",
        pt="fecho de Kleene",
        tags=["foundations"],
    ),
    dict(
        q="What is a <b>(formal) language</b>?",
        a="Any <b>set of strings</b> over an alphabet — i.e. any subset L ⊆ Σ*. It can be finite, infinite, or even empty.",
        ex="L = {0<sup>n</sup>1<sup>n</sup> : n ≥ 0} = {ε, 01, 0011, 000111, …} is a language over {0,1}. The whole course is about which <i>machines</i> can recognize which <i>languages</i>.",
        pt="linguagem formal",
        tags=["foundations"],
    ),
    dict(
        q="What is the difference between <b>∅</b>, <b>{ε}</b>, and <b>ε</b>?",
        a="<b>∅</b> = the empty language (no strings at all).<br><b>{ε}</b> = a language containing exactly one string, the empty one.<br><b>ε</b> = the empty string itself (a string, not a language).",
        ex="A machine recognizing ∅ accepts nothing; a machine recognizing {ε} accepts only the empty input. Exams love this distinction.",
        pt="linguagem vazia vs. palavra vazia",
        tags=["foundations"],
    ),
    dict(
        q="Define the <b>length</b> |w| and <b>concatenation</b> xy of strings.",
        a="|w| = number of symbols in w (|ε| = 0).<br>Concatenation xy = write x, then write y right after it. |xy| = |x| + |y|.",
        ex="x = ab, y = ba → xy = abba. Concatenation is associative but NOT commutative (xy ≠ yx in general).",
        pt="comprimento; concatenação",
        tags=["foundations"],
    ),
    dict(
        q="What are the three <b>regular operations</b> on languages A and B?",
        a="<b>Union:</b> A ∪ B = {w : w ∈ A or w ∈ B}<br><b>Concatenation:</b> A∘B = {xy : x ∈ A, y ∈ B}<br><b>Star:</b> A* = {x₁x₂…x<sub>k</sub> : k ≥ 0, each xᵢ ∈ A}",
        ex="Note A* always contains ε (take k = 0). If A = {0, 11} then A* = {ε, 0, 11, 011, 110, 00, 1111, …}.",
        pt="operações regulares: união, concatenação, estrela",
        tags=["foundations"],
    ),
    dict(
        q="What is the <b>complement</b> of a language L over Σ?",
        a="L̄ = Σ* \\ L — all strings over the alphabet that are <b>not</b> in L.",
        ex="If L = strings containing '00', then L̄ = strings with no two consecutive 0s.",
        pt="complemento",
        tags=["foundations"],
    ),
    dict(
        q="What is the <b>power set</b> P(A) of a set A, and how big is it?",
        a="The set of all subsets of A. If |A| = n, then |P(A)| = 2<sup>n</sup>.",
        ex="P({x,y}) = {∅, {x}, {y}, {x,y}}. Used in the NFA→DFA subset construction, where DFA states are <i>sets</i> of NFA states.",
        pt="conjunto das partes / conjunto potência",
        tags=["foundations"],
    ),
    dict(
        q="When is a function f: A → B <b>injective</b>, <b>surjective</b>, <b>bijective</b>?",
        a="<b>Injective (1-to-1):</b> different inputs give different outputs.<br><b>Surjective (onto):</b> every element of B is hit.<br><b>Bijective:</b> both — a perfect pairing of A and B.",
        ex="A bijection between A and B means they have 'the same size' — this is how we compare sizes of infinite sets.",
        pt="injetora, sobrejetora, bijetora",
        tags=["foundations"],
    ),
    dict(
        q="What is an <b>equivalence relation</b>?",
        a="A relation that is:<br>• <b>reflexive</b>: x ~ x<br>• <b>symmetric</b>: x ~ y ⟹ y ~ x<br>• <b>transitive</b>: x ~ y and y ~ z ⟹ x ~ z<br>It partitions the set into disjoint <b>equivalence classes</b>.",
        ex="'Same remainder mod 3' partitions ℕ into 3 classes. The Myhill–Nerode theorem uses an equivalence relation on strings to characterize regular languages.",
        pt="relação de equivalência; classes de equivalência",
        tags=["foundations"],
    ),
    dict(
        q="When is a set called <b>countable</b>?",
        a="When it is finite, or when there is a bijection between it and ℕ = {1, 2, 3, …} — i.e. you can <b>list its elements</b> e₁, e₂, e₃, … without missing any.",
        ex="ℤ and even ℚ (the rationals) are countable. Σ* is countable: list strings by length, then alphabetically.",
        pt="conjunto enumerável / contável",
        tags=["foundations"],
    ),
    dict(
        q="Describe <b>Cantor's diagonalization</b> argument (why ℝ is uncountable).",
        a="Suppose all infinite binary sequences could be listed s₁, s₂, s₃, … Build a new sequence d whose i-th bit is the <b>flipped</b> i-th bit of sᵢ. Then d differs from every sᵢ (at position i), so d is not in the list — contradiction. No list can cover them all.",
        ex="This exact trick reappears twice in the course: (1) more languages than Turing machines exist; (2) the proof that A<sub>TM</sub> is undecidable.",
        pt="diagonalização de Cantor",
        tags=["foundations", "keyproof"],
    ),
    dict(
        q="Why must there exist languages that <b>no program/Turing machine can recognize</b>?",
        a="A counting argument:<br>• The set of Turing machines is <b>countable</b> (each has a finite description).<br>• The set of languages over Σ is <b>uncountable</b> (it's P(Σ*), the power set of an infinite set — diagonalization).<br>Countably many machines can't cover uncountably many languages.",
        ex="This proves unsolvable problems exist <i>before</i> exhibiting one. The halting problem is the famous concrete example.",
        pt="existem linguagens não reconhecíveis",
        tags=["foundations", "keyproof"],
    ),
    dict(
        q="What is the structure of a <b>proof by induction</b>?",
        a="To prove P(n) for all n ≥ 0:<br>1. <b>Base case:</b> prove P(0).<br>2. <b>Inductive step:</b> assume P(k) (induction hypothesis) and prove P(k+1).",
        ex="In this course you often induct on the <b>length of a string</b> or the <b>number of steps of a derivation/computation</b>.",
        pt="prova por indução",
        tags=["foundations"],
    ),
    dict(
        q="What is the structure of a <b>proof by contradiction</b>?",
        a="Assume the statement is <b>false</b>, derive something impossible, conclude the statement must be true.",
        ex="Standard template for non-regularity: 'Assume L is regular. Then the pumping lemma applies… but pumping produces a string outside L. Contradiction, so L is not regular.'",
        pt="prova por contradição / redução ao absurdo",
        tags=["foundations"],
    ),
    dict(
        q="State the <b>pigeonhole principle</b>. Where does it show up in this course?",
        a="If you put more than n objects into n boxes, some box gets ≥ 2 objects.",
        ex="It's the engine of the pumping lemma: a DFA with p states reading a string of length ≥ p must <b>repeat a state</b> — that repeated state creates a pumpable loop.",
        pt="princípio da casa dos pombos",
        tags=["foundations"],
    ),
    dict(
        q="In graph terms, what is a <b>directed graph</b>, a <b>path</b>, and a <b>cycle</b>?",
        a="Directed graph: nodes + arrows (edges with direction).<br>Path: sequence of nodes connected by edges.<br>Cycle: path that starts and ends at the same node.",
        ex="Automata are drawn as directed graphs: states = nodes, transitions = labeled arrows. Many NP-complete problems (HAMPATH, CLIQUE) are graph problems.",
        pt="grafo dirigido, caminho, ciclo",
        tags=["foundations"],
    ),
    dict(
        q="What is a <b>decision problem</b>, and how is it modeled as a language?",
        a="A problem whose answer is <b>yes or no</b> for each input. It is modeled as the language of all inputs whose answer is 'yes' (encoded as strings). Solving the problem = recognizing/deciding that language.",
        ex="'Is n prime?' becomes the language PRIMES = {⟨n⟩ : n is prime}. This is why the whole course talks about languages instead of 'problems'.",
        pt="problema de decisão",
        tags=["foundations"],
    ),
    dict(
        q="What does the notation <b>⟨O⟩</b> mean, e.g. ⟨M⟩ or ⟨G, w⟩?",
        a="The <b>encoding</b> of object O as a string, so it can be fed as input to a machine. ⟨M, w⟩ encodes a pair (a machine M and a string w) as a single string.",
        ex="Any reasonable encoding works (e.g. write the transition table in binary). This lets machines take <i>other machines</i> as input — the key to universality and undecidability.",
        pt="codificação de objetos como cadeias",
        tags=["foundations"],
    ),
]
