"""Section 1: Finite automata and regular languages."""

CARDS = [
    dict(
        q="Give the formal definition of a <b>DFA</b> (deterministic finite automaton).",
        a="A 5-tuple M = (Q, Σ, δ, q₀, F):<br>• Q — finite set of <b>states</b><br>• Σ — input <b>alphabet</b><br>• δ: Q × Σ → Q — <b>transition function</b><br>• q₀ ∈ Q — <b>start state</b><br>• F ⊆ Q — set of <b>accept (final) states</b>",
        ex="'Deterministic' = from each state, each symbol leads to <b>exactly one</b> next state. No choices, no ε-moves.",
        pt="autômato finito determinístico (AFD)",
        tags=["regular", "definition"],
    ),
    dict(
        q="When does a DFA <b>accept</b> a string w = w₁w₂…wₙ?",
        a="Start at q₀; read the symbols one by one, following δ at each step; accept iff the state reached <b>after the last symbol</b> is in F.",
        ex="One single run per string — deterministic. If the final state ∉ F, the string is rejected. ε is accepted iff q₀ ∈ F.",
        pt="aceitação por AFD",
        tags=["regular", "definition"],
    ),
    dict(
        q="What is <b>L(M)</b>, the language of a machine M?",
        a="The set of <b>all strings that M accepts</b>: L(M) = {w : M accepts w}. We say M <b>recognizes</b> L(M).",
        ex="A machine recognizes exactly ONE language, even if it accepts many strings. If M accepts no strings, L(M) = ∅.",
        pt="linguagem reconhecida pela máquina",
        tags=["regular", "definition"],
    ),
    dict(
        q="What is a <b>regular language</b>?",
        a="A language recognized by <b>some DFA</b> (equivalently: some NFA, or some regular expression).",
        ex="Intuition: languages decidable with a <b>fixed, finite amount of memory</b>, no matter how long the input is.",
        pt="linguagem regular",
        tags=["regular", "definition"],
    ),
    dict(
        q="Design idea: a DFA for 'binary strings with an <b>even number of 0s</b>'.",
        a="Two states remembering the parity: q_even (start, accepting) and q_odd. Reading 0 swaps the state; reading 1 stays. Accept in q_even.",
        ex="Design recipe: ask '<b>what must I remember</b> about the prefix read so far?' — each distinct 'memory' becomes a state.",
        pt="projeto de AFD",
        tags=["regular", "technique"],
    ),
    dict(
        q="Give the formal definition of an <b>NFA</b> and list how it differs from a DFA.",
        a="N = (Q, Σ, δ, q₀, F) with δ: Q × Σ<sub>ε</sub> → <b>P(Q)</b> (power set). Differences:<br>• a state may have <b>zero, one, or many</b> arrows for a symbol<br>• <b>ε-transitions</b>: change state without reading input<br>• output of δ is a <b>set</b> of states",
        ex="Σ<sub>ε</sub> means Σ ∪ {ε}. 'N' = nondeterministic.",
        pt="autômato finito não determinístico (AFN)",
        tags=["regular", "definition"],
    ),
    dict(
        q="When does an <b>NFA accept</b> a string?",
        a="If <b>at least one</b> possible computation path (sequence of choices, including ε-moves) ends in an accept state. It rejects only if <b>every</b> path fails.",
        ex="Think of it as parallel copies of the machine, or as guessing: 'the NFA guesses the right path'. Only existence of one good path matters.",
        pt="aceitação por AFN",
        tags=["regular", "definition"],
    ),
    dict(
        q="Are NFAs <b>more powerful</b> than DFAs (do they recognize more languages)?",
        a="<b>No.</b> Every NFA has an equivalent DFA (subset construction). NFAs and DFAs recognize exactly the regular languages — NFAs are just more <i>convenient</i> (often exponentially smaller).",
        ex="Classic exam trap: nondeterminism adds no power for <i>finite automata</i> (unlike for pushdown automata, where it does).",
        pt="equivalência AFN–AFD",
        tags=["regular", "theorem"],
    ),
    dict(
        q="Explain the <b>subset (powerset) construction</b> NFA → DFA.",
        a="Each DFA state is a <b>set of NFA states</b> ('all places the NFA could be right now'). Start state: ε-closure of q₀. Transition: from set S on symbol a, go to the ε-closure of all states reachable from S. Accept: any set containing an NFA accept state.",
        ex="An NFA with n states gives a DFA with at most <b>2ⁿ</b> states — and this exponential blowup is sometimes unavoidable.",
        pt="construção de subconjuntos",
        tags=["regular", "technique"],
    ),
    dict(
        q="Are the regular languages closed under <b>union, concatenation, and star</b>? How is it proved?",
        a="<b>Yes, all three.</b> Proofs use NFAs:<br>• Union: new start state with ε-arrows to both machines.<br>• Concatenation: ε-arrows from accept states of the 1st machine to the start of the 2nd.<br>• Star: ε-arrows from accept states back to start, plus a new accepting start state.",
        ex="These three constructions are exactly why nondeterminism is convenient — try doing concatenation directly with DFAs!",
        pt="fechamento sob operações regulares",
        tags=["regular", "closure"],
    ),
    dict(
        q="Are regular languages closed under <b>complement</b> and <b>intersection</b>?",
        a="<b>Yes.</b><br>• Complement: take a DFA and <b>swap accepting and non-accepting states</b> (must be a DFA, not an NFA!).<br>• Intersection: product construction, or use A ∩ B = (A̅ ∪ B̅)̅ (De Morgan).",
        ex="Swapping accept states of an <i>NFA</i> does NOT complement its language — a string can have both accepting and rejecting paths. Classic exam question.",
        pt="fechamento sob complemento e interseção",
        tags=["regular", "closure"],
    ),
    dict(
        q="Describe the <b>product construction</b> for the intersection of two regular languages.",
        a="Given DFAs M₁, M₂, build a DFA whose states are <b>pairs</b> (q, r) — one state from each machine — and run both in parallel: δ((q,r), a) = (δ₁(q,a), δ₂(r,a)). Accept iff <b>both</b> components accept.",
        ex="For union, accept iff <b>at least one</b> component accepts. State count: |Q₁| × |Q₂|.",
        pt="construção do produto",
        tags=["regular", "technique"],
    ),
    dict(
        q="Give the inductive definition of a <b>regular expression</b> over Σ.",
        a="Base cases: <b>a</b> (for a ∈ Σ), <b>ε</b>, <b>∅</b>.<br>Inductive cases: if R₁, R₂ are regexes, so are <b>(R₁ ∪ R₂)</b>, <b>(R₁∘R₂)</b>, and <b>(R₁*)</b>.<br>Precedence: star > concatenation > union.",
        ex="R∪∅ = R, R∘ε = R, but R∘∅ = ∅ and ∅* = {ε}. These identities show up in written exams.",
        pt="expressão regular",
        tags=["regular", "definition"],
    ),
    dict(
        q="What is <b>Kleene's theorem</b> (the equivalence theorem for regular languages)?",
        a="A language is regular ⟺ some regular expression describes it. So <b>DFA ≡ NFA ≡ regex</b>: all three formalisms define exactly the same class of languages.",
        ex="Conversions: regex → NFA (build small machines for the pieces, glue with ε-arrows) and DFA → regex (state elimination via GNFA).",
        pt="teorema de Kleene",
        tags=["regular", "theorem"],
    ),
    dict(
        q="How do you convert a <b>regular expression to an NFA</b>?",
        a="Structural induction (Thompson's construction): build tiny NFAs for a, ε, ∅; then combine them with the ε-arrow constructions for union, concatenation, and star, following the structure of the expression.",
        ex="(ab ∪ a)* → build NFA for ab, NFA for a, join for union, then apply the star construction.",
        pt="conversão de expressão regular para AFN",
        tags=["regular", "technique"],
    ),
    dict(
        q="How do you convert a <b>DFA to a regular expression</b>?",
        a="Via a <b>GNFA</b> (generalized NFA whose arrows are labeled with regexes): add a new start and accept state, then <b>rip out states one by one</b>, repairing paths by composing labels — when q is removed, each path i→q→j becomes label R<sub>iq</sub>(R<sub>qq</sub>)*R<sub>qj</sub>, unioned with the old R<sub>ij</sub>.",
        ex="After all internal states are removed, the single remaining arrow's label is the answer.",
        pt="eliminação de estados (GNFA)",
        tags=["regular", "technique"],
    ),
    dict(
        q="Write regular expressions over {0,1} for:<br>(a) strings ending in 01;<br>(b) strings containing 11;<br>(c) strings of even length.",
        a="(a) (0∪1)*01<br>(b) (0∪1)*11(0∪1)*<br>(c) ((0∪1)(0∪1))*",
        ex="Pattern library worth memorizing: 'contains x' = Σ*xΣ*; 'starts with x' = xΣ*; 'ends with x' = Σ*x.",
        pt="exemplos de expressões regulares",
        tags=["regular", "technique"],
    ),
    dict(
        q="State the <b>pumping lemma for regular languages</b> — with all three conditions.",
        a="If L is regular, there is a <b>pumping length p</b> such that every s ∈ L with |s| ≥ p can be split s = <b>xyz</b> where:<br>1. <b>xyⁱz ∈ L for every i ≥ 0</b> (pumping up and down)<br>2. <b>|y| > 0</b> (y is non-empty)<br>3. <b>|xy| ≤ p</b> (the loop occurs in the first p symbols)",
        ex="Why it's true: with p states, reading p symbols must repeat a state (pigeonhole) — y is the loop between the repeats, and loops can be taken 0, 1, 2, … times.",
        pt="lema do bombeamento para linguagens regulares",
        tags=["regular", "pumping", "theorem"],
    ),
    dict(
        q="What is the <b>proof template</b> for showing L is NOT regular with the pumping lemma?",
        a="1. Assume L is regular; let p be its pumping length.<br>2. <b>Choose cleverly ONE string s ∈ L</b>, |s| ≥ p (you pick s; it may depend on p).<br>3. For <b>every</b> split s = xyz satisfying |y| > 0 and |xy| ≤ p…<br>4. …exhibit an i (often 0 or 2) with xyⁱz ∉ L.<br>5. Contradiction ⟹ L is not regular.",
        ex="Think of it as a game vs. an adversary: the adversary picks p and the split; you pick s and i. Condition |xy| ≤ p is your friend — it pins y down inside the first p symbols.",
        pt="prova de não-regularidade",
        tags=["regular", "pumping", "technique"],
    ),
    dict(
        q="Prove that <b>L = {0ⁿ1ⁿ : n ≥ 0}</b> is not regular.",
        a="Take s = 0<sup>p</sup>1<sup>p</sup> ∈ L. Any valid split s = xyz has |xy| ≤ p, so <b>y consists only of 0s</b> (and y ≠ ε). Pump: xy²z has more 0s than 1s ⟹ ∉ L. Contradiction.",
        ex="The canonical example. Intuition: a finite automaton cannot <b>count unboundedly</b> — it would need a state for each possible count.",
        pt="{0ⁿ1ⁿ} não é regular",
        tags=["regular", "pumping", "keyproof"],
    ),
    dict(
        q="Name four classic <b>non-regular</b> languages (besides 0ⁿ1ⁿ).",
        a="• {ww : w ∈ {0,1}*} (repeated string)<br>• {w : w is a palindrome}<br>• {0<sup>n²</sup> : n ≥ 0} (perfect-square lengths)<br>• {0<sup>p</sup> : p prime}<br>All require unbounded counting/matching.",
        ex="For the last two, pump on <b>length arithmetic</b>: consecutive squares/primes get arbitrarily far apart, but pumping changes length by a fixed amount |y| each time.",
        pt="linguagens não regulares clássicas",
        tags=["regular", "pumping"],
    ),
    dict(
        q="Can the pumping lemma be used to prove that a language <b>IS</b> regular?",
        a="<b>No.</b> It states a necessary condition, not a sufficient one: regular ⟹ pumpable. Some non-regular languages satisfy the pumping conditions. To prove regularity, exhibit a DFA/NFA/regex.",
        ex="Direction of logic matters: the lemma is only a weapon <b>against</b> regularity (via contrapositive).",
        pt="lema do bombeamento é condição necessária, não suficiente",
        tags=["regular", "pumping"],
    ),
    dict(
        q="When are two strings x, y <b>distinguishable</b> by a language L?",
        a="When there exists an <b>extension z</b> such that exactly one of xz, yz is in L. If no such z exists, x and y are <b>indistinguishable</b> (L-equivalent, x ≡<sub>L</sub> y).",
        ex="For L = {0ⁿ1ⁿ}: 0² and 0³ are distinguished by z = 11 (0²11 ∈ L, 0³11 ∉ L). A DFA must send distinguishable strings to <b>different states</b>.",
        pt="cadeias distinguíveis",
        tags=["regular", "myhillnerode", "definition"],
    ),
    dict(
        q="State the <b>Myhill–Nerode theorem</b>.",
        a="L is regular ⟺ the indistinguishability relation ≡<sub>L</sub> has <b>finitely many equivalence classes</b>. Moreover, the number of classes = number of states of the <b>minimal DFA</b> for L.",
        ex="Two superpowers: (1) prove non-regularity by exhibiting infinitely many pairwise-distinguishable strings; (2) prove a DFA is minimal. Unlike the pumping lemma, it's an exact characterization.",
        pt="teorema de Myhill–Nerode",
        tags=["regular", "myhillnerode", "theorem"],
    ),
    dict(
        q="Use Myhill–Nerode to show {0ⁿ1ⁿ} is not regular.",
        a="The strings 0¹, 0², 0³, … are <b>pairwise distinguishable</b>: for i ≠ j, the extension z = 1ⁱ gives 0ⁱ1ⁱ ∈ L but 0ʲ1ⁱ ∉ L. Infinitely many equivalence classes ⟹ not regular.",
        ex="Often cleaner than the pumping lemma — no case analysis over splits.",
        pt="não-regularidade via Myhill–Nerode",
        tags=["regular", "myhillnerode", "keyproof"],
    ),
    dict(
        q="Which <b>decision problems about regular languages</b> are decidable (algorithmically solvable)?",
        a="All the standard ones:<br>• <b>Membership</b> (does M accept w?) — run the DFA<br>• <b>Emptiness</b> (L(M) = ∅?) — check if any accept state is reachable from start<br>• <b>Equivalence</b> (L(M₁) = L(M₂)?) — check emptiness of the symmetric difference (built via product + complement)",
        ex="Contrast to remember: for CFGs, equivalence is undecidable; for TMs, even emptiness and membership are undecidable.",
        pt="problemas decidíveis sobre linguagens regulares",
        tags=["regular", "decidability"],
    ),
    dict(
        q="Is every <b>finite</b> language regular?",
        a="<b>Yes.</b> A finite language {w₁, …, w<sub>k</sub>} is a finite union of singletons, each described by a regex; union of regulars is regular.",
        ex="Consequence: non-regular languages are always infinite. But not every infinite language is non-regular ((0∪1)* is infinite and regular).",
        pt="toda linguagem finita é regular",
        tags=["regular"],
    ),
    dict(
        q="True or false: if L₁ and L₂ are <b>not</b> regular, then L₁ ∪ L₂ is not regular.",
        a="<b>False.</b> Non-closure tricks: take any non-regular L. Then L̄ is also non-regular (complement closure), but L ∪ L̄ = Σ*, which is regular.",
        ex="Closure works one way only: regular ops on <i>regular</i> languages give regular results. It says nothing about combining non-regular ones.",
        pt="cuidado com fechamento reverso",
        tags=["regular", "closure", "trap"],
    ),
    dict(
        q="Is the class of regular languages closed under <b>reversal</b>?",
        a="<b>Yes.</b> Reverse all arrows of a DFA/NFA, make the old start state accepting, and add a new start state with ε-arrows to the old accept states — the result recognizes L<sup>R</sup> = {w<sup>R</sup> : w ∈ L}.",
        ex="Also closed under: homomorphism, inverse homomorphism, difference (A \\ B = A ∩ B̄), symmetric difference.",
        pt="fechamento sob reversão",
        tags=["regular", "closure"],
    ),
    dict(
        q="Summarize: what can a finite automaton <b>fundamentally not do</b>?",
        a="It cannot store an <b>unbounded amount of information</b> — it has no memory beyond its current state. Anything requiring unbounded counting, matching, or comparison of distant parts is non-regular.",
        ex="Rule of thumb: 'need to count arbitrarily high or remember an arbitrary string' ⟹ not regular. 'Need only a bounded summary (parity, remainder, last k symbols, seen-a-pattern flag)' ⟹ regular.",
        pt="limitações dos autômatos finitos",
        tags=["regular", "intuition"],
    ),
]
