"""Section 3: Turing machines and the Church-Turing thesis."""

CARDS = [
    dict(
        q="Describe a <b>Turing machine (TM)</b> informally. What are its components?",
        a="A finite control (like a DFA) plus an <b>infinite tape</b> and a <b>head</b> that can:<br>• <b>read and write</b> symbols on the tape<br>• move <b>left and right</b><br>The input starts on the tape; the rest is blank (␣). It halts immediately upon entering its accept or reject state.",
        ex="Proposed by Alan Turing (1936) as a formal model of 'a person computing with pencil and paper'. It is THE definition of 'algorithm' in this course.",
        pt="máquina de Turing (MT)",
        tags=["turing", "definition"],
    ),
    dict(
        q="Give the formal <b>7-tuple definition</b> of a Turing machine.",
        a="M = (Q, Σ, Γ, δ, q₀, q<sub>accept</sub>, q<sub>reject</sub>):<br>• Q — states; Σ — input alphabet (␣ ∉ Σ)<br>• Γ — tape alphabet, with ␣ ∈ Γ and Σ ⊆ Γ<br>• δ: Q × Γ → Q × Γ × {L, R} — read a symbol ⟹ write a symbol, move Left/Right, change state<br>• q₀ start; q<sub>accept</sub> ≠ q<sub>reject</sub> halting states",
        ex="Compare with DFA: the TM can WRITE, move BOTH directions, has unlimited tape, and can run forever.",
        pt="definição formal da MT",
        tags=["turing", "definition"],
    ),
    dict(
        q="What are the <b>three possible outcomes</b> of running a TM on an input?",
        a="1. <b>Accept</b> (reaches q<sub>accept</sub>)<br>2. <b>Reject</b> (reaches q<sub>reject</sub>)<br>3. <b>Loop</b> — runs forever, never halting.",
        ex="The third outcome is the whole drama of computability theory. A DFA always halts (input is finite); a TM might not.",
        pt="aceitar, rejeitar, entrar em loop",
        tags=["turing", "definition"],
    ),
    dict(
        q="What is a <b>configuration</b> of a Turing machine?",
        a="A complete snapshot of the computation: current <b>state</b>, current <b>tape contents</b>, and current <b>head position</b>. Written as <b>uqv</b>: tape is uv, state is q, head on the first symbol of v.",
        ex="A computation is a sequence of configurations, each yielding the next. Cook–Levin later encodes such sequences as a Boolean formula — configurations are worth understanding well.",
        pt="configuração",
        tags=["turing", "definition"],
    ),
    dict(
        q="Define <b>Turing-recognizable</b> (= recursively enumerable, r.e.).",
        a="L is Turing-recognizable if some TM M <b>accepts exactly the strings of L</b>. On strings NOT in L, M may reject <b>or loop forever</b>.",
        ex="'Recognizer' gives a one-sided guarantee: yes-instances are eventually accepted; no-instances might leave you waiting forever without an answer.",
        pt="Turing-reconhecível / recursivamente enumerável",
        tags=["turing", "definition"],
    ),
    dict(
        q="Define <b>decidable</b> (= recursive) language and <b>decider</b>.",
        a="L is decidable if some TM accepts every w ∈ L and rejects every w ∉ L — i.e. it <b>halts on all inputs</b>. Such an always-halting TM is called a <b>decider</b>.",
        ex="Decider = algorithm in the everyday sense: guaranteed to finish with a correct yes/no. Every decidable language is recognizable; the converse fails (A<sub>TM</sub>).",
        pt="linguagem decidível / recursiva; decisor",
        tags=["turing", "definition"],
    ),
    dict(
        q="What is the relationship: <b>L decidable ⟺ ?</b> (in terms of recognizability of L and its complement)",
        a="<b>L is decidable ⟺ both L and its complement L̄ are Turing-recognizable.</b><br>(⟸: run the recognizer for L and the one for L̄ in parallel on w; exactly one must eventually accept — answer accordingly.)",
        ex="A language whose complement is recognizable is called <b>co-Turing-recognizable</b>. Consequence: since A<sub>TM</sub> is recognizable but undecidable, its complement is NOT recognizable.",
        pt="decidível = reconhecível e co-reconhecível",
        tags=["turing", "theorem", "keyproof"],
    ),
    dict(
        q="Is a <b>multitape</b> Turing machine more powerful than a single-tape one?",
        a="<b>No</b> — same class of languages. A single tape simulates k tapes by storing all of them on one tape separated by markers, with 'dotted' symbols marking the k head positions; each step scans the tape to update all virtual heads.",
        ex="Cost: t(n) steps of the multitape TM take O(t(n)²) single-tape steps — power unchanged, only <i>speed</i> differs (matters later in complexity).",
        pt="MT multifita ≡ MT de uma fita",
        tags=["turing", "theorem"],
    ),
    dict(
        q="Is a <b>nondeterministic</b> Turing machine (NTM) more powerful than a deterministic one?",
        a="<b>No</b> — same class of languages. A deterministic TM simulates an NTM by exploring its computation tree <b>breadth-first</b> (trying all choice sequences by increasing length).",
        ex="Why breadth-first, not depth-first? A depth-first search could dive into an infinite non-accepting branch and miss an accepting one. (Whether the simulation can avoid exponential slowdown = the P vs NP question!)",
        pt="MT não determinística ≡ determinística",
        tags=["turing", "theorem"],
    ),
    dict(
        q="What is an <b>enumerator</b>, and what does it characterize?",
        a="A TM with a printer that runs forever, <b>printing strings</b> (possibly with repeats, in any order). <b>L is Turing-recognizable ⟺ some enumerator prints exactly L.</b>",
        ex="This is why recognizable languages are called 'recursively <b>enumerable</b>'. Direction recognizer→enumerator uses dovetailing: run the recognizer i steps on each of the first i strings, for i = 1, 2, 3, …",
        pt="enumerador",
        tags=["turing", "theorem"],
    ),
    dict(
        q="State the <b>Church–Turing thesis</b>. Is it a theorem?",
        a="<b>Thesis:</b> the intuitive notion of 'algorithm' (effectively computable procedure) corresponds exactly to what Turing machines can compute.<br><b>Not a theorem</b> — it can't be proved, because 'intuitive algorithm' is not a formal notion. It is universally accepted because every proposed model (λ-calculus, RAM, your favorite programming language, quantum computers*) computes the same class of functions.",
        ex="*Quantum computers may be <i>faster</i> but compute the same set of functions. Practical consequence: in proofs you may describe algorithms in high-level pseudocode instead of building explicit TMs.",
        pt="tese de Church–Turing",
        tags=["turing", "bigpicture"],
    ),
    dict(
        q="What is the <b>universal Turing machine</b> U?",
        a="A single TM that takes ⟨M, w⟩ (a description of any TM M and an input w) and <b>simulates M running on w</b> — accepting/rejecting/looping just as M would.",
        ex="Conceptually: the first 'stored-program computer' — hardware (U) separate from software (⟨M⟩). U is exactly the recognizer for A<sub>TM</sub>.",
        pt="máquina de Turing universal",
        tags=["turing", "definition"],
    ),
    dict(
        q="Why can a Turing machine's <b>description be given as a string</b>, and why does this matter?",
        a="A TM is a finite object (finitely many states, symbols, transitions), so it can be encoded as a finite string ⟨M⟩. This means: machines can be <b>inputs to other machines</b>, TMs can be listed M₁, M₂, … (countably many), and self-reference becomes possible.",
        ex="All three consequences fuel the undecidability results: universal machine, counting argument, diagonalization.",
        pt="codificação de MTs",
        tags=["turing", "bigpicture"],
    ),
    dict(
        q="Order these classes and give a separating example for each inclusion:<br>regular, context-free, decidable, Turing-recognizable.",
        a="regular ⊊ context-free ⊊ decidable ⊊ Turing-recognizable<br>• {0ⁿ1ⁿ}: CF, not regular<br>• {aⁿbⁿcⁿ}: decidable, not CF<br>• A<sub>TM</sub>: recognizable, not decidable<br>(and beyond: complement of A<sub>TM</sub> is not even recognizable)",
        ex="This is the course's master picture — memorize it cold, with the witnesses.",
        pt="hierarquia de classes de linguagens",
        tags=["turing", "bigpicture"],
    ),
    dict(
        q="Sketch how a TM decides <b>{0ⁿ1ⁿ : n ≥ 0}</b> (which no finite automaton can).",
        a="Repeatedly: scan the tape, <b>cross off one 0 and one 1</b> per pass; reject if the symbols run out unevenly or appear out of order; accept when all symbols are crossed off.",
        ex="Even {aⁿbⁿcⁿ}, beyond PDAs, is easy for TMs (cross off one of each per pass). The tape is reusable random-access memory.",
        pt="MT para 0ⁿ1ⁿ",
        tags=["turing", "technique"],
    ),
    dict(
        q="What does it mean to say an <b>algorithm exists</b> for a problem, formally?",
        a="There is a <b>Turing machine that decides</b> the corresponding language: it halts on every input with the correct yes/no answer.",
        ex="Historical origin: Hilbert's 10th problem asked for an 'algorithm' for Diophantine equations before 'algorithm' had a definition. The TM supplied the definition — and then the problem was proved unsolvable (Matiyasevich, 1970).",
        pt="algoritmo = decisor",
        tags=["turing", "bigpicture"],
    ),
]
